import re
import uuid
from typing import List, Dict, Any, Optional

class Document:
    def __init__(self, content: str, metadata: Optional[Dict[str, Any]] = None):
        self.id = str(uuid.uuid4())
        self.content = content
        self.metadata = metadata or {}

class RetrievalResult:
    def __init__(self, document: Document, score: float):
        self.document = document
        self.score = score
        self.citation = f"[{self.document.metadata.get('source', 'Unknown')}]: {self.document.content[:50]}..."

class BaseRetriever:
    """
    Interface cơ sở cho Retriever.
    Kiến trúc này giúp dễ dàng thay thế MockRetriever bằng VectorDB thật (như ChromaDB) sau này.
    """
    def add_documents(self, documents: List[Document]) -> None:
        raise NotImplementedError

    def retrieve(self, query: str, top_k: int = 3) -> List[RetrievalResult]:
        raise NotImplementedError


import json
import os

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

class MockRetriever(BaseRetriever):
    def __init__(self):
        self.documents: List[Document] = []
        # Path to the actual KB file generated by the scraper
        self.db_path = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "knowledge_base.json")
        self.vectorizer = None
        self.tfidf_matrix = None
        self._load_db()
        
    def _save_db(self):
        data = [{"content": d.content, "metadata": d.metadata} for d in self.documents]
        with open(self.db_path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)

    def _build_index(self):
        if not self.documents:
            return
        corpus = [d.content for d in self.documents]
        # Sử dụng TfidfVectorizer như một VectorDB dạng thưa (Sparse Vector)
        self.vectorizer = TfidfVectorizer(max_df=0.85)
        self.tfidf_matrix = self.vectorizer.fit_transform(corpus)

    def _load_db(self):
        if os.path.exists(self.db_path):
            with open(self.db_path, "r", encoding="utf-8") as f:
                data = json.load(f)
                for item in data:
                    self.documents.append(Document(item["content"], item["metadata"]))
            self._build_index()

    def add_documents(self, documents: List[Document]) -> None:
        self.documents.extend(documents)
        self._save_db()
        self._build_index()
        
    def retrieve(self, query: str, top_k: int = 3) -> List[RetrievalResult]:
        if not self.vectorizer or not self.tfidf_matrix is not None:
            return []
            
        # Biến đổi query thành vector
        query_vec = self.vectorizer.transform([query])
        
        # Tính khoảng cách toán học (Cosine Similarity)
        cosine_similarities = cosine_similarity(query_vec, self.tfidf_matrix).flatten()
        
        # Lấy top k kết quả
        related_docs_indices = cosine_similarities.argsort()[:-top_k-1:-1]
        
        results = []
        for idx in related_docs_indices:
            score = cosine_similarities[idx]
            if score > 0:
                # Chuẩn hóa score để khớp với logic cũ (nhân lên để không bị loại)
                normalized_score = float(score * 3.0) 
                results.append(RetrievalResult(self.documents[idx], normalized_score))
                
        return results


class BaseReranker:
    """
    Interface cơ sở cho Reranker (VD: Cross-Encoder).
    """
    def rerank(self, query: str, results: List[RetrievalResult]) -> List[RetrievalResult]:
        raise NotImplementedError

class MockReranker(BaseReranker):
    """
    Mô phỏng Reranker: Tăng điểm nếu document chứa cụm từ chính xác (exact phrase).
    """
    def rerank(self, query: str, results: List[RetrievalResult]) -> List[RetrievalResult]:
        query_lower = query.lower()
        for res in results:
            if query_lower in res.document.content.lower():
                res.score += 2.0  # Tăng điểm mạnh nếu khớp cả cụm
            
        results.sort(key=lambda x: x.score, reverse=True)
        return results

import chromadb
from chromadb.utils import embedding_functions

class ChromaRetriever(BaseRetriever):
    """
    Retriever thực tế kết nối với Cơ sở dữ liệu Vector (ChromaDB) ở ổ D.
    (Áp dụng cho Phase 2)
    """
    def __init__(self, collection_name="vimedai_knowledge"):
        self.db_path = r"d:\AI_HoSoBenhAn\vector_db"
        self.collection_name = collection_name
        self.client = chromadb.PersistentClient(path=self.db_path)
        self.ef = embedding_functions.SentenceTransformerEmbeddingFunction(model_name="keepitreal/vietnamese-sbert")
        
        try:
            self.collection = self.client.get_collection(name=self.collection_name, embedding_function=self.ef)
        except Exception as e:
            print(f"Tạo mới collection rỗng do chưa có sẵn: {e}")
            self.collection = self.client.create_collection(name=self.collection_name, embedding_function=self.ef)
            
    def add_documents(self, documents: List[Document]) -> None:
        # Việc Ingest dữ liệu đã được tách riêng ra module ingestor.py
        pass
        
    def retrieve(self, query: str, top_k: int = 3) -> List[RetrievalResult]:
        try:
            # Query thẳng vào ChromaDB, tự động convert text -> vector
            results = self.collection.query(
                query_texts=[query],
                n_results=top_k
            )
            
            retrieval_results = []
            if results and results['documents'] and results['documents'][0]:
                for i in range(len(results['documents'][0])):
                    doc_content = results['documents'][0][i]
                    metadata = results['metadatas'][0][i] if results['metadatas'] else {}
                    
                    # ChromaDB trả về khoảng cách (distance). Điểm càng nhỏ càng gần.
                    # Đảo ngược lại thành Score (càng cao càng tốt)
                    distance = results['distances'][0][i] if 'distances' in results and results['distances'] else 1.0
                    # Tinh chỉnh lại score cho phù hợp với logic cũ
                    score = max(0, 1.0 - (distance / 2.0)) * 5.0
                    
                    doc = Document(content=doc_content, metadata=metadata)
                    retrieval_results.append(RetrievalResult(doc, score))
                    
            return retrieval_results
        except Exception as e:
            print(f"Lỗi truy vấn ChromaDB: {e}")
            return []

class ClinicalRAG:
    """
    Module 5: Truy hồi và Neo đầu ra (Modular RAG)
    """
    def __init__(self, retriever: Optional[BaseRetriever] = None, reranker: Optional[BaseReranker] = None):
        # Cho phép Dependency Injection. Giai đoạn 2 mặc định dùng ChromaRetriever!
        try:
            self.retriever = retriever or ChromaRetriever()
        except Exception as e:
            print(f"[RAG] Lỗi kết nối ChromaDB, tự động Fallback về MockRetriever: {e}")
            self.retriever = retriever or MockRetriever()
            
        self.reranker = reranker or MockReranker()
        
    def index_document(self, content: str, source: str = "Tài liệu Y khoa", metadata: Optional[Dict[str, Any]] = None) -> str:
        """
        UC-RAG-01: Quản lý kho tri thức y khoa.
        Lập chỉ mục tài liệu.
        """
        meta = metadata or {}
        meta["source"] = source
        doc = Document(content=content, metadata=meta)
        self.retriever.add_documents([doc])
        return doc.id
        
    def retrieve_context(self, query: str, top_k: int = 3) -> Dict[str, Any]:
        """
        UC-RAG-02: Truy hồi, Rerank và Citation.
        """
        # Retrieval Stage (lấy nhiều hơn để rerank)
        results = self.retriever.retrieve(query, top_k=top_k * 2)
        
        # Rerank Stage
        results = self.reranker.rerank(query, results)
        results = results[:top_k]
        
        contexts = []
        citations = []
        for res in results:
            contexts.append(res.document.content)
            citations.append({
                "id": res.document.id,
                "source": res.document.metadata.get("source"),
                "metadata": res.document.metadata,
                "text_snippet": res.document.content[:100],
                "score": res.score
            })
            
        return {
            "query": query,
            "combined_context": "\n\n".join(contexts),
            "citations": citations
        }

    def check_faithfulness(self, generated_text: str, context: str) -> Dict[str, Any]:
        """
        UC-RAG-03: Kiểm tra độ trung thực (Faithfulness Check).
        """
        unsupported_claims = []
        
        # Rule đơn giản: Trích xuất các thực thể In Hoa (VD: Paracetamol) hoặc 
        # số đi kèm đơn vị (VD: 39 độ, 500mg) từ generated_text. Dùng \w để hỗ trợ tiếng Việt.
        entities = re.findall(r'\b[A-ZĐ][\w]+\b|\b\d+(?:\.\d+)?\s*\w+\b', generated_text)
        
        context_lower = context.lower()
        for entity in entities:
            # Bỏ qua các từ thông thường như "HÀNH CHÍNH" (uppercase all) do regex trên chỉ bắt Title Case
            if entity.lower() not in context_lower:
                unsupported_claims.append(entity)
                
        is_faithful = len(unsupported_claims) == 0
        return {
            "is_faithful": is_faithful,
            "unsupported_claims": list(set(unsupported_claims))
        }
